### ISSUE TITLE
Review Checklist

### ISSUE THREAD

**Issue by huangs1** [ZachAndrews98/GroupMeBot#9]
- [X] Project Name and Description

- [X] How to Build and Run the Project

- [x] How to Test the Application

- [X] Software Tools Used

- [X] Tangible Results

- [X] Travis CI Integration

- [X] Use of Github Flow

- [X] Use of Standard Directory Conventions

- [X] License
